export const ROUTER_PATHS = {
  main: "/",
  category: "/category",
  categoryDetail: "/category/:id",
  product: "/product/:id",
  favorites: "/favorites",
  cart: "/cart",
  contacts: "/contacts",
  search: "/search",
  about: "/about",
  jobs: "/jobs",
  article: "/article/:id",
  privacyPolicy: "/privacy-policy",
  orders: "/orders",
};
